// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXV8gAy1muuHAh81AKE2xYzpzakrK3ZxA',
    appId: '1:359722216524:web:6a35f31e46f861a5b358e9',
    messagingSenderId: '359722216524',
    projectId: 'note-project-655b8',
    authDomain: 'note-project-655b8.firebaseapp.com',
    storageBucket: 'note-project-655b8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAozBSYgiLxST-JMSphTDxBtCYRaV3BiHk',
    appId: '1:359722216524:android:6c3c2499f9a95bc7b358e9',
    messagingSenderId: '359722216524',
    projectId: 'note-project-655b8',
    storageBucket: 'note-project-655b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD4ZFg2sZ9PGwo1JRWZF93huUVFw5rZzw',
    appId: '1:359722216524:ios:f5b74cf9b6684420b358e9',
    messagingSenderId: '359722216524',
    projectId: 'note-project-655b8',
    storageBucket: 'note-project-655b8.appspot.com',
    androidClientId: '359722216524-bfi04rr44crrc1viigai7583e58v4s20.apps.googleusercontent.com',
    iosClientId: '359722216524-vbbfuprnpeh81jkic6rm2tu757cmfpks.apps.googleusercontent.com',
    iosBundleId: 'com.example.noteProject',
  );
}
